export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const USER_LOADING = "USER_LOADING"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_FORGOT_SUCCESS = "USER_FORGOT_SUCCESS"
export const USER_RESET_SUCCESS = "USER_RESET_SUCCESS"
export const USER_FAIL = "USER_FAIL"
export const VALID_USER_LOGOUT_SUCCESS = "VALID_USER_LOGOUT_SUCCESS"

export const GET_BASKET_SUCCESS="GET_BASKET_SUCCESS"
export const BASKET_REQUEST="BASKET_REQUEST"
export const BASKET_FAILURE="BASKET_FAILURE"


export const GET_SYMBOLS_SUCCESS="GET_SYMBOLS_SUCCESS"
export const SYMBOLS_REQUEST="SYMBOLS_REQUEST"
export const SYMBOLS_FAILURE="SYMBOLS_FAILURE"
export const GET_UNDERLYING_INDEX_SUCCESS = "GET_UNDERLYING_INDEX_SUCCESS";
export const UNDERLYING_INDEX_FAILURE = "UNDERLYING_INDEX_FAILURE";
export const UNDERLYING_INDEX_REQUEST = "UNDERLYING_INDEX_REQUEST";

export const GET_CLIENTS_SUCCESS="GET_CLIENTS_SUCCESS"
export const CLIENTS_REQUEST="CLIENTS_REQUEST"
export const CLIENTS_FAILURE="CLIENTS_FAILURE"





export const GET_RESEARCH_ANALYSTS_REQUEST="GET_RESEARCH_ANALYSTS_REQUEST"
export const GET_RESEARCH_ANALYSTS_SUCCESS="GET_RESEARCH_ANALYSTS_SUCCESS"
export const GET_RESEARCH_ANALYSTS_FAILURE="GET_RESEARCH_ANALYSTS_FAILURE"
export const GET_DEALERS_REQUEST="GET_DEALERS_REQUEST"
export const GET_DEALERS_SUCCESS="GET_DEALERS_SUCCESS"
export const GET_DEALERS_FAILURE="GET_DEALERS_FAILURE"
export const POST_RESEARCH_ANALYST_REQUEST="POST_RESEARCH_ANALYST_REQUEST"
export const POST_RESEARCH_ANALYST_SUCCESS="POST_RESEARCH_ANALYST_SUCCESS"
export const POST_RESEARCH_ANALYST_FAILURE="POST_RESEARCH_ANALYST_FAILURE"
export const POST_DEALER_REQUEST="POST_DEALER_REQUEST"
export const POST_DEALER_SUCCESS="POST_DEALER_SUCCESS"
export const POST_DEALER_FAILURE="POST_DEALER_FAILURE"

// Existing action types...
export const UPDATE_DEALER_STATUS_REQUEST = "UPDATE_DEALER_STATUS_REQUEST";
export const UPDATE_DEALER_STATUS_SUCCESS = "UPDATE_DEALER_STATUS_SUCCESS";
export const UPDATE_DEALER_STATUS_FAILURE = "UPDATE_DEALER_STATUS_FAILURE";



export const GET_ALGO_REQUEST = 'GET_ALGO_REQUEST';
export const GET_ALGO_SUCCESS = 'GET_ALGO_SUCCESS';
export const GET_ALGO_FAILURE = 'GET_ALGO_FAILURE';

export const GET_SIGNAL_REQUEST = 'GET_SIGNAL_REQUEST';
export const GET_SIGNAL_SUCCESS = 'GET_SIGNAL_SUCCESS';
export const GET_SIGNAL_FAILURE = 'GET_SIGNAL_FAILURE';