export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const USER_LOADING = "USER_LOADING"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_FORGOT_SUCCESS = "USER_FORGOT_SUCCESS"
export const USER_RESET_SUCCESS = "USER_RESET_SUCCESS"
export const USER_FAIL = "USER_FAIL"
export const VALID_USER_LOGOUT_SUCCESS = "VALID_USER_LOGOUT_SUCCESS"

export const GET_BASKET_SUCCESS="GET_BASKET_SUCCESS"
export const BASKET_REQUEST="BASKET_REQUEST"
export const BASKET_FAILURE="BASKET_FAILURE"


export const GET_SYMBOLS_SUCCESS="GET_SYMBOLS_SUCCESS"
export const SYMBOLS_REQUEST="SYMBOLS_REQUEST"
export const SYMBOLS_FAILURE="SYMBOLS_FAILURE"